Update matrix-bot-sdk to latest and Node to v18
matrix-org/conference-bot pull request #163
Opened 2023-01-31 16:47 UTC by Half-Shot

Node version changes are *usually* safe as long as we test it on staging first, and bot-sdk requires at least v16.

2023-02-03 16:17 UTC, reivilibre approved these changes

2023-02-03 16:17 UTC, reivilibre commented on .github/workflows/pipeline.yml
> +      - uses: actions/setup-node@v3 # "v1.3.0"
I think the comment here is stale & below.

2023-02-03 16:18 UTC, Half-Shot commented on .github/workflows/pipeline.yml
> +      - uses: actions/setup-node@v3 # "v1.3.0"
whoops yes

2023-02-03 16:19 UTC, turt2live requested changes
I would recommend not deploying this today. Maybe Monday.

2023-10-05 09:56 UTC, Half-Shot commented
I suspect Monday has passed and we can now do this.

2023-10-05 09:56 UTC, merged