Add more specific errors to `CopyModerators` command
matrix-org/conference-bot pull request #196
Opened 2023-11-07 20:17 UTC by H-Shay

Part of the effort to improve error messages. I hate that it is a pile of try/catch but I wasn't sure how else to give more specific information about where things are failing. Suggestions welcome.

2023-11-07 20:18 UTC, H-Shay commented on src/commands/HelpCommand.ts
> +            "!conference join &lt;room&gt;             - Makes the bot join the given room.\n" +
This was just a typo I noticed that was causing the last two help commands to not be shown in the client. Drive-by cleanup.

2023-11-07 22:04 UTC, Half-Shot requested changes
Errors are good, just wanted to call out some good practice stuff.

2023-11-07 22:04 UTC, Half-Shot commented on src/commands/CopyModeratorsCommand.ts
> +            throw Error(`Error fetching or processing power level event from room ${fromRoomId}: ${error.toString()}`)
Same as other review on `cause` usage

2023-11-07 22:04 UTC, Half-Shot commented on src/commands/CopyModeratorsCommand.ts
> +        let fromPl: { "users"?: Record<string, any> } = {}
`PowerLevelsEventContent` may also work here?

2023-11-07 22:04 UTC, Half-Shot commented on src/commands/CopyModeratorsCommand.ts
> +            var toPl = await this.client.getRoomStateEvent(toRoomId, "m.room.power_levels", "");
```suggestion
        let toPl: PowerLevelsEventContent;
        try {
            toPl = await this.client.getRoomStateEvent(toRoomId, "m.room.power_levels", "");
```

Avoid using `var` if you can, it doesn't conform to block scoping and tends to surprise you. In this case TypeScript should let you define `toPl` outside and it will always be set, because you are throwing.

2023-11-07 22:04 UTC, Half-Shot commented on src/commands/CopyModeratorsCommand.ts
> +            throw Error(`Error fetching or processing power level event from room ${toRoomId}: ${error.toString()}`)
cause etc

2023-11-08 13:33 UTC, reivilibre commented on src/commands/HelpCommand.ts
> +            "!conference join &lt;room&gt;             - Makes the bot join the given room.\n" +
I hate how JavaScript is happy to have these implied semicolons lead to effectively empty / ignored statements. Thanks for catching it :-)

2023-11-08 22:58 UTC, H-Shay commented on src/commands/CopyModeratorsCommand.ts
> +        let fromPl: { "users"?: Record<string, any> } = {}
It does - much nicer, thanks!

2023-11-09 09:41 UTC, Half-Shot approved these changes
Terrific. Thanks!

2023-11-09 16:17 UTC, merged

2023-11-09 16:18 UTC, H-Shay commented
Merged #196 into main, thanks for the review!