Ensure we don't accidentally send out invites when testing
matrix-org/conference-bot pull request #209
Opened 2024-01-12 23:37 UTC by H-Shay

Temporary hack to reduce sharp edges since we will be testing against the live prod pretalx server.

2024-01-15 16:47 UTC, Half-Shot requested changes
I'm a little worried about checking in code that disables the invite logic, if we can figure out a flag instead that would make this more valuable.

2024-01-15 16:47 UTC, Half-Shot commented on src/IRCBridge.ts
> +            //await this.mxClient.inviteUser(this.config.botUserId, roomId);
This is probably fine as-is, it's for the IRC bridge which we're not using this year.

2024-01-15 16:47 UTC, Half-Shot commented on src/invites.ts
>  export async function invitePersonToRoom(client: ConferenceMatrixClient, resolvedPerson: ResolvedPersonIdentifier, roomId: string): Promise<void> {
I wonder if we can slip in a dry-run flag in the config, and just skip this function if so? Worst case, maybe we just override the inviteUser function in `ConferenceMatrixClient`.

2024-01-16 19:22 UTC, H-Shay commented on src/invites.ts
>  export async function invitePersonToRoom(client: ConferenceMatrixClient, resolvedPerson: ResolvedPersonIdentifier, roomId: string): Promise<void> {
A dry run flag is a much better approach - I've added one, let me know what you think.

2024-01-16 22:51 UTC, Half-Shot approved these changes
Looks great. I've suggested we log that we log dry run when dry running a command to prevent confusion (esp if we toggle it on/off). 

Feel free to merge when you're happy!

2024-01-16 22:51 UTC, Half-Shot commented on src/invites.ts
> +            LogService.info("invites", `Third-party inviting ${email}`)
```suggestion
            LogService.info("invites", `Third-party inviting ${email} (dry-run)`)
```

2024-01-16 22:51 UTC, Half-Shot commented on src/invites.ts
> +            LogService.info("invites", `Inviting ${resolvedPerson.mxid}`)
```suggestion
            LogService.info("invites", `Inviting ${resolvedPerson.mxid} (dry-run)`)
```

2024-01-16 22:51 UTC, Half-Shot commented on config/default.yaml
> +# if set to "true" will prevent the conf-bot from sending live invites to email/matrix_ids
ultra tiny nit but just because for a second I thought this was a string, backticks are a slightly better way to represent

```suggestion
# if set to `true` will prevent the conf-bot from sending live invites to email/matrix_ids
```

2024-01-16 23:38 UTC, merged

2024-01-16 23:38 UTC, H-Shay commented
Merged #209 into main.