Update auditorium names to be the track name on talk start
matrix-org/conference-bot pull request #230
Opened 2024-02-04 10:42 UTC by reivilibre

pulled from FOSDEM 2024 Hotfixes #228 

A nice-to-have would be to update on Sunday before the first talk even starts (and maybe slightly in advance of the changeover halfway through the day too).

But that would have been complicated to do and we needed something simple and robust on the day.

2024-02-04 12:17 UTC, Half-Shot requested changes

2024-02-04 12:17 UTC, Half-Shot commented on src/Scheduler.ts
> +                if (task.talk.track != '' && task.talk.track != undefined && task.talk.track != nameEventContent["name"]) {
You can test some of these conditions prior to pulling state.

2024-02-04 12:17 UTC, Half-Shot commented on src/Scheduler.ts
> +                LogService.error("Scheduler:talkStart", `Error when considering changing name of track room: ${e}`);
So we get a stacktrace.

```suggestion
                LogService.error("Scheduler:talkStart", `Error when considering changing name of track room`, e);
```

2024-02-04 12:30 UTC, reivilibre commented on src/Scheduler.ts
> +                if (task.talk.track != '' && task.talk.track != undefined && task.talk.track != nameEventContent["name"]) {
That's true. In some respects I'm not expecting these things to happen, but I just didn't want the bot to go and do a silly if they actually did.

2024-02-12 11:20 UTC, Half-Shot approved these changes

2024-02-23 16:52 UTC, merged