Allow configuration of multiple moderator users to be invited to all rooms.
matrix-org/conference-bot pull request #234
Opened 2024-11-28 14:04 UTC by reivilibre

We want the ability to invite someone else alongside the moderator bot, in all rooms.

This makes `moderatorUserId` an array instead, `moderatorUserIds` but otherwise the semantics should be all the same?

2024-12-03 09:00 UTC, Half-Shot requested changes
The template thing bugs me, but it might just be hard to tell from the review window.

I'd *like* to say if we have the time then a test (based maybe off https://github.com/matrix-org/conference-bot/blob/main/spec/basic.spec.ts#L24-L48) would be helpful here to ensure behavior.

2024-12-03 11:37 UTC, reivilibre commented on src/models/room_kinds.ts
> +    invite: moderatorUserIds,
as you point out, this is probably broken. We haven't used special interest rooms for at least a couple of years now so I guess it wouldn't be a surprise. I may as well fix that obvious part up now though

2024-12-16 14:11 UTC, reivilibre commented on spec/util/e2e-test.ts
> +            moderatorUserIds: [`@modbot:${homeserver.domain}`],
wrote this now, a little fiddly but I think it's better than nothing? :-)

2024-12-16 14:12 UTC, reivilibre commented on src/Conference.ts
> +            for (let moderator of this.config.moderatorUserIds) {
I feel more happy leaving it as it is (in a 'known working' state) than messing TBH. It is a shame that these don't compose well though.

2024-12-16 14:37 UTC, Half-Shot approved these changes
Looks good to me, one question.

2024-12-16 14:37 UTC, Half-Shot commented on src/config.ts
> +    moderatorUserIds: string[];
Do we want to still have the legacy moderatorUserId option, which we internally convert to `moderatorUserIds` at runtime just for anyone running an old config.

Or failing that, warn on startup that the old field is unused?

2024-12-16 14:41 UTC, reivilibre commented on src/config.ts
> +    moderatorUserIds: string[];
refusing to start up seems like a reasonable option. I don't think we should force ourselves into too much backwards compat given we don't expect anyone else to be running this really. But refusing to start up sounds like a decent footgun-avoider.

2024-12-17 12:39 UTC, Half-Shot approved these changes

2024-12-17 12:41 UTC, merged